// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeMovieHandlerServer is an autogenerated mock type for the UnsafeMovieHandlerServer type
type UnsafeMovieHandlerServer struct {
	mock.Mock
}

// mustEmbedUnimplementedMovieHandlerServer provides a mock function with given fields:
func (_m *UnsafeMovieHandlerServer) mustEmbedUnimplementedMovieHandlerServer() {
	_m.Called()
}
