// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package movie_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MovieHandlerClient is the client API for MovieHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MovieHandlerClient interface {
	GetMovie(ctx context.Context, in *SingleRequest, opts ...grpc.CallOption) (*Movie, error)
	FetchMovie(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (MovieHandler_FetchMovieClient, error)
}

type movieHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewMovieHandlerClient(cc grpc.ClientConnInterface) MovieHandlerClient {
	return &movieHandlerClient{cc}
}

func (c *movieHandlerClient) GetMovie(ctx context.Context, in *SingleRequest, opts ...grpc.CallOption) (*Movie, error) {
	out := new(Movie)
	err := c.cc.Invoke(ctx, "/movie_grpc.MovieHandler/GetMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieHandlerClient) FetchMovie(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (MovieHandler_FetchMovieClient, error) {
	stream, err := c.cc.NewStream(ctx, &MovieHandler_ServiceDesc.Streams[0], "/movie_grpc.MovieHandler/FetchMovie", opts...)
	if err != nil {
		return nil, err
	}
	x := &movieHandlerFetchMovieClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MovieHandler_FetchMovieClient interface {
	Recv() (*Movie, error)
	grpc.ClientStream
}

type movieHandlerFetchMovieClient struct {
	grpc.ClientStream
}

func (x *movieHandlerFetchMovieClient) Recv() (*Movie, error) {
	m := new(Movie)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MovieHandlerServer is the server API for MovieHandler service.
// All implementations must embed UnimplementedMovieHandlerServer
// for forward compatibility
type MovieHandlerServer interface {
	GetMovie(context.Context, *SingleRequest) (*Movie, error)
	FetchMovie(*FetchRequest, MovieHandler_FetchMovieServer) error
	mustEmbedUnimplementedMovieHandlerServer()
}

// UnimplementedMovieHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedMovieHandlerServer struct {
}

func (UnimplementedMovieHandlerServer) GetMovie(context.Context, *SingleRequest) (*Movie, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMovie not implemented")
}
func (UnimplementedMovieHandlerServer) FetchMovie(*FetchRequest, MovieHandler_FetchMovieServer) error {
	return status.Errorf(codes.Unimplemented, "method FetchMovie not implemented")
}
func (UnimplementedMovieHandlerServer) mustEmbedUnimplementedMovieHandlerServer() {}

// UnsafeMovieHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MovieHandlerServer will
// result in compilation errors.
type UnsafeMovieHandlerServer interface {
	mustEmbedUnimplementedMovieHandlerServer()
}

func RegisterMovieHandlerServer(s grpc.ServiceRegistrar, srv MovieHandlerServer) {
	s.RegisterService(&MovieHandler_ServiceDesc, srv)
}

func _MovieHandler_GetMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieHandlerServer).GetMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/movie_grpc.MovieHandler/GetMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieHandlerServer).GetMovie(ctx, req.(*SingleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieHandler_FetchMovie_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MovieHandlerServer).FetchMovie(m, &movieHandlerFetchMovieServer{stream})
}

type MovieHandler_FetchMovieServer interface {
	Send(*Movie) error
	grpc.ServerStream
}

type movieHandlerFetchMovieServer struct {
	grpc.ServerStream
}

func (x *movieHandlerFetchMovieServer) Send(m *Movie) error {
	return x.ServerStream.SendMsg(m)
}

// MovieHandler_ServiceDesc is the grpc.ServiceDesc for MovieHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MovieHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "movie_grpc.MovieHandler",
	HandlerType: (*MovieHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMovie",
			Handler:    _MovieHandler_GetMovie_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FetchMovie",
			Handler:       _MovieHandler_FetchMovie_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "movie.proto",
}
